version: '3.9'

services:
  db:
    image: postgres:15.1-alpine
    container_name: beer_rater_fast_api_db
    env_file:
      - .env
    volumes:
      - beer-rater-fast-api-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 2s
      timeout: 3s
      retries: 40
  app:
    build:
      context: .
    container_name: beer_rater_fast_api_app
    ports:
      - 8000:8000
    volumes:
      - ./app/:/project/app/
    depends_on:
      db:
        condition: service_healthy
volumes:
  beer-rater-fast-api-data:
    driver: local
